Not Found: /api/fetch_notification_status/1
Bad Request: /api/send_notification
Bad Request: /api/subscribe
Watching for file changes with StatReloader
/Users/alias/Documents/PushOwl-tr/pushNotification/pushNotification/settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/push/subscription/36/change/ HTTP/1.1" 200 9774
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /admin/push/subscription/36/change/ HTTP/1.1" 302 0
"GET /admin/push/subscription/ HTTP/1.1" 200 9631
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
/Users/alias/Documents/PushOwl-tr/pushNotification/push/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
Watching for file changes with StatReloader
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
/Users/alias/Documents/PushOwl-tr/pushNotification/push/services/SubscriptionService.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
Watching for file changes with StatReloader
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
/Users/alias/Documents/PushOwl-tr/pushNotification/push/services/SubscriptionService.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
"GET /admin/push/subscription/36/change/ HTTP/1.1" 200 9782
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /admin/push/subscription/36/change/ HTTP/1.1" 302 0
"GET /admin/push/subscription/ HTTP/1.1" 200 9631
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
Internal Server Error: /api/subscribe
Traceback (most recent call last):
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/alias/Documents/PushOwl-tr/pushNotification/push/views.py", line 30, in subscribe_client
    "response": updated_subscription_serializer.initial_data,
AttributeError: 'SubscriptionSerializer' object has no attribute 'initial_data'
"POST /api/subscribe HTTP/1.1" 500 102208
/Users/alias/Documents/PushOwl-tr/pushNotification/push/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/push/subscription/36/change/ HTTP/1.1" 200 9787
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /admin/push/subscription/36/change/ HTTP/1.1" 302 0
"GET /admin/push/subscription/ HTTP/1.1" 200 9631
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /api/subscribe HTTP/1.1" 200 408
/Users/alias/Documents/PushOwl-tr/pushNotification/push/services/SubscriptionService.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/push/subscription/36/change/ HTTP/1.1" 200 9787
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /admin/push/subscription/36/change/ HTTP/1.1" 302 0
"GET /admin/push/subscription/ HTTP/1.1" 200 9631
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /api/subscribe HTTP/1.1" 200 408
"GET /admin/push/subscription/36/change/ HTTP/1.1" 200 9787
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /admin/push/subscription/36/change/ HTTP/1.1" 302 0
"GET /admin/push/subscription/ HTTP/1.1" 200 9631
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
"POST /api/subscribe HTTP/1.1" 200 409
Watching for file changes with StatReloader
Not Found: /api/fetch_notification_status/1
Bad Request: /api/send_notification
Bad Request: /api/subscribe
"GET /admin/push/subscription/ HTTP/1.1" 200 9190
"GET /admin/jsi18n/ HTTP/1.1" 200 3195
Watching for file changes with StatReloader
"OPTIONS /api/subscribe HTTP/1.1" 200 0
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
"GET /admin/push/notification/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/push/notification/ HTTP/1.1" 200 2250
"GET /static/admin/css/login.css HTTP/1.1" 200 939
"OPTIONS /api/subscribe HTTP/1.1" 200 0
Bad Request: /api/subscribe
"POST /api/subscribe HTTP/1.1" 400 64
Not Found: /api/fetch_notification_status/1
Bad Request: /api/send_notification
Bad Request: /api/subscribe
